import type { StyleSpecification } from "maplibre-gl";

export const base: StyleSpecification = {
  version: 8,
  name: "Default",
  center: [8.54806714892635, 47.37180823552663],
  zoom: 12.241790506353492,
  bearing: 0,
  pitch: 0,
  sources: {
    openmaptiles: {
      type: "vector",
      url: "https://tiles.openfreemap.org/planet",
      attribution:
        '<a href="https://openfreemap.org/" target="_blank">&copy; OpenFreeMap!</a> <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>',
    },
  },
  layers: [
    // {
    //   id: "landuse-residential",
    //   type: "fill",
    //   source: "openmaptiles",
    //   "source-layer": "landuse",
    //   filter: [
    //     "all",
    //     ["==", ["geometry-type"], "Polygon"],
    //     ["==", ["get", "class"], "residential"],
    //   ],
    //   layout: { visibility: "none" },
    //   paint: { "fill-color": "hsl(47,13%,86%)", "fill-opacity": 0.7 },
    // },
    // {
    //   id: "landcover_grass",
    //   type: "fill",
    //   source: "openmaptiles",
    //   "source-layer": "landcover",
    //   filter: ["==", ["get", "class"], "grass"],
    //   layout: { visibility: "none" },
    //   paint: { "fill-color": "hsl(82,46%,72%)", "fill-opacity": 0.45 },
    // },
    // {
    //   id: "landcover_wood",
    //   type: "fill",
    //   source: "openmaptiles",
    //   "source-layer": "landcover",
    //   filter: ["==", ["get", "class"], "wood"],
    //   layout: { visibility: "none" },
    //   paint: {
    //     "fill-color": "rgb(74 93 65)",
    //     "fill-opacity": ["interpolate", ["linear"], ["zoom"], 8, 0.6, 22, 1],
    //   },
    // },
    // {
    //   id: "park",
    //   type: "fill",
    //   source: "openmaptiles",
    //   "source-layer": "park",
    //   layout: { visibility: "none" },
    //   paint: { "fill-color": "rgba(192, 216, 151, 0.53)", "fill-opacity": 1 },
    // },
    // {
    //   id: "landcover-ice-shelf",
    //   type: "fill",
    //   source: "openmaptiles",
    //   "source-layer": "landcover",
    //   filter: ["==", ["get", "subclass"], "ice_shelf"],
    //   layout: { visibility: "none" },
    //   paint: { "fill-color": "#797B77", "fill-opacity": 0.8 },
    // },
    // {
    //   id: "landcover-glacier",
    //   type: "fill",
    //   source: "openmaptiles",
    //   "source-layer": "landcover",
    //   filter: ["==", ["get", "subclass"], "glacier"],
    //   layout: { visibility: "none" },
    //   paint: {
    //     "fill-color": "hsl(47,22%,94%)",
    //     "fill-opacity": ["interpolate", ["linear"], ["zoom"], 0, 1, 8, 0.5],
    //   },
    // },
    // {
    //   id: "landcover_sand",
    //   type: "fill",
    //   metadata: {},
    //   source: "openmaptiles",
    //   "source-layer": "landcover",
    //   filter: ["match", ["get", "class"], ["sand"], true, false],
    //   layout: { visibility: "none" },
    //   paint: {
    //     "fill-antialias": false,
    //     "fill-color": "rgb(74 93 65)",
    //     "fill-opacity": 0.3,
    //   },
    // },
    // {
    //   id: "landuse",
    //   type: "fill",
    //   source: "openmaptiles",
    //   "source-layer": "landuse",
    //   filter: ["==", ["get", "class"], "agriculture"],
    //   layout: { visibility: "none" },
    //   paint: { "fill-color": "#eae0d0" },
    // },
    // {
    //   id: "landuse_overlay_national_park",
    //   type: "fill",
    //   source: "openmaptiles",
    //   "source-layer": "landcover",
    //   filter: ["==", ["get", "class"], "national_park"],
    //   layout: { visibility: "none" },
    //   paint: {
    //     "fill-color": "#E1EBB0",
    //     "fill-opacity": ["interpolate", ["linear"], ["zoom"], 5, 0, 9, 0.75],
    //   },
    // },
    // {
    //   id: "park_outline",
    //   type: "line",
    //   source: "openmaptiles",
    //   "source-layer": "park",
    //   layout: { visibility: "none" },
    //   paint: {
    //     "line-color": "rgba(159, 183, 118, 0.69)",
    //     "line-dasharray": [0.5, 1],
    //   },
    // },
    {
      id: "water",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "water",
      filter: [
        "all",
        ["==", ["geometry-type"], "Polygon"],
        ["!=", ["get", "brunnel"], "tunnel"],
        ["!=", ["get", "class"], "swimming_pool"],
      ],
      paint: { "fill-color": "#8191B2" },
    },
    {
      id: "waterway-tunnel",
      type: "line",
      source: "openmaptiles",
      "source-layer": "waterway",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["==", ["get", "brunnel"], "tunnel"],
      ],
      paint: {
        "line-color": "#8191B2",
        "line-dasharray": [3, 3],
        "line-gap-width": ["interpolate", ["linear"], ["zoom"], 12, 0, 20, 6],
        "line-opacity": 1,
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          8,
          1,
          20,
          2,
        ],
      },
    },
    {
      id: "waterway",
      type: "line",
      source: "openmaptiles",
      "source-layer": "waterway",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["match", ["get", "brunnel"], ["bridge", "tunnel"], false, true],
      ],
      paint: {
        "line-color": "#8191B2",
        "line-opacity": 1,
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          8,
          1,
          20,
          8,
        ],
      },
    },
    {
      id: "tunnel_railway_transit",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 0,
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["==", ["get", "brunnel"], "tunnel"],
        ["==", ["get", "class"], "transit"],
      ],
      layout: { "line-cap": "butt", "line-join": "miter", visibility: "none" },
      paint: {
        "line-color": "hsl(34,12%,66%)",
        "line-dasharray": [3, 3],
        "line-opacity": ["interpolate", ["linear"], ["zoom"], 11, 0, 16, 1],
      },
    },
    // {
    //   id: "building",
    //   type: "fill",
    //   source: "openmaptiles",
    //   "source-layer": "building",
    //   layout: { visibility: "none" },
    //   paint: {
    //     "fill-color": "hsl(39,41%,86%)",
    //     "fill-opacity": ["interpolate", ["linear"], ["zoom"], 13, 0.6, 14, 1],
    //     "fill-outline-color": "hsl(36,45%,80%)",
    //   },
    // },
    {
      id: "road_area_pier",
      type: "fill",
      metadata: {},
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "Polygon"],
        ["==", ["get", "class"], "pier"],
      ],
      layout: { visibility: "none" },
      paint: { "fill-antialias": true, "fill-color": "#797B77" },
    },
    {
      id: "road_pier",
      type: "line",
      metadata: {},
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["match", ["get", "class"], ["pier"], true, false],
      ],
      layout: { "line-cap": "round", "line-join": "round", visibility: "none" },
      paint: {
        "line-color": "#797B77",
        "line-width": [
          "interpolate",
          ["exponential", 1.2],
          ["zoom"],
          15,
          1,
          17,
          4,
        ],
      },
    },
    {
      id: "road_bridge_area",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "Polygon"],
        ["match", ["get", "brunnel"], ["bridge"], true, false],
      ],
      layout: { visibility: "none" },
      paint: { "fill-color": "#797B77" },
    },
    // {
    //   id: "road_path",
    //   type: "line",
    //   source: "openmaptiles",
    //   "source-layer": "transportation",
    //   filter: [
    //     "all",
    //     ["==", ["geometry-type"], "LineString"],
    //     ["match", ["get", "class"], ["path", "track"], true, false],
    //   ],
    //   layout: {
    //     "line-cap": "square",
    //     "line-join": "bevel",
    //     visibility: "none",
    //   },
    //   paint: {
    //     "line-color": "hsl(0,0%,97%)",
    //     "line-dasharray": [1, 1],
    //     "line-width": [
    //       "interpolate",
    //       ["exponential", 1.55],
    //       ["zoom"],
    //       4,
    //       0.25,
    //       20,
    //       10,
    //     ],
    //   },
    // },
    // {
    //   id: "road_minor",
    //   type: "line",
    //   source: "openmaptiles",
    //   "source-layer": "transportation",
    //   filter: [
    //     "all",
    //     ["==", ["geometry-type"], "LineString"],
    //     ["match", ["get", "class"], ["minor", "service"], true, false],
    //   ],
    //   layout: { "line-cap": "round", "line-join": "round", visibility: "none" },
    //   paint: {
    //     "line-color": "hsl(0,0%,97%)",
    //     "line-width": [
    //       "interpolate",
    //       ["exponential", 1.55],
    //       ["zoom"],
    //       4,
    //       0.25,
    //       20,
    //       30,
    //     ],
    //   },
    // },
    // {
    //   id: "tunnel_minor",
    //   type: "line",
    //   source: "openmaptiles",
    //   "source-layer": "transportation",
    //   filter: [
    //     "all",
    //     ["==", ["geometry-type"], "LineString"],
    //     [
    //       "all",
    //       ["==", ["get", "brunnel"], "tunnel"],
    //       ["==", ["get", "class"], "minor_road"],
    //     ],
    //   ],
    //   layout: { "line-cap": "butt", "line-join": "miter", visibility: "none" },
    //   paint: {
    //     "line-color": "#efefef",
    //     "line-dasharray": [0.36, 0.18],
    //     "line-width": [
    //       "interpolate",
    //       ["exponential", 1.55],
    //       ["zoom"],
    //       4,
    //       0.25,
    //       20,
    //       30,
    //     ],
    //   },
    // },
    // {
    //   id: "tunnel_major",
    //   type: "line",
    //   source: "openmaptiles",
    //   "source-layer": "transportation",
    //   filter: [
    //     "all",
    //     ["==", ["geometry-type"], "LineString"],
    //     [
    //       "all",
    //       ["==", ["get", "brunnel"], "tunnel"],
    //       [
    //         "match",
    //         ["get", "class"],
    //         ["primary", "secondary", "tertiary", "trunk"],
    //         true,
    //         false,
    //       ],
    //     ],
    //   ],
    //   layout: { "line-cap": "butt", "line-join": "miter", visibility: "none" },
    //   paint: {
    //     "line-color": "#797B77",
    //     "line-dasharray": [0.28, 0.14],
    //     "line-width": [
    //       "interpolate",
    //       ["exponential", 1.4],
    //       ["zoom"],
    //       6,
    //       0.5,
    //       20,
    //       30,
    //     ],
    //   },
    // },
    {
      id: "road_trunk_primary",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["match", ["get", "class"], ["primary", "trunk"], true, false],
      ],
      layout: { "line-cap": "round", "line-join": "round", visibility: "none" },
      paint: {
        "line-color": "#797B77",
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          2,
          0.1,
          20,
          30,
        ],
      },
    },
    {
      id: "road_secondary_tertiary",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["match", ["get", "class"], ["secondary", "tertiary"], true, false],
      ],
      layout: { "line-cap": "round", "line-join": "round", visibility: "none" },
      paint: {
        "line-color": "#797B77",
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          6,
          0.5,
          20,
          20,
        ],
      },
    },
    {
      id: "road_major_motorway",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["==", ["get", "class"], "motorway"],
      ],
      layout: { "line-cap": "round", "line-join": "round", visibility: "none" },
      paint: {
        "line-color": "#797B77",
        "line-offset": 0,
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          2.2,
          0.5,
          16,
          10,
        ],
      },
    },
    {
      id: "railway_transit",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["get", "class"], "transit"],
        ["!=", ["get", "brunnel"], "tunnel"],
      ],
      layout: { visibility: "none" },
      paint: {
        "line-color": "hsl(34,12%,66%)",
        "line-opacity": ["interpolate", ["linear"], ["zoom"], 11, 0, 16, 1],
      },
    },
    {
      id: "railway",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: ["==", ["get", "class"], "rail"],
      layout: { visibility: "none" },
      paint: {
        "line-color": "hsl(34,12%,66%)",
        "line-opacity": ["interpolate", ["linear"], ["zoom"], 11, 0, 16, 1],
      },
    },
    {
      id: "waterway-bridge-case",
      type: "line",
      source: "openmaptiles",
      "source-layer": "waterway",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["==", ["get", "brunnel"], "bridge"],
      ],
      layout: { "line-cap": "butt", "line-join": "miter", visibility: "none" },
      paint: {
        "line-color": "#bbbbbb",
        "line-gap-width": [
          "interpolate",
          ["exponential", 1.55],
          ["zoom"],
          4,
          0.25,
          20,
          30,
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.6],
          ["zoom"],
          12,
          0.5,
          20,
          10,
        ],
      },
    },
    {
      id: "waterway-bridge",
      type: "line",
      source: "openmaptiles",
      "source-layer": "waterway",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["==", ["get", "brunnel"], "bridge"],
      ],
      layout: { "line-cap": "round", "line-join": "round", visibility: "none" },
      paint: {
        "line-color": "hsl(205,56%,73%)",
        "line-width": [
          "interpolate",
          ["exponential", 1.55],
          ["zoom"],
          4,
          0.25,
          20,
          30,
        ],
      },
    },
    // {
    //   id: "bridge_minor case",
    //   type: "line",
    //   source: "openmaptiles",
    //   "source-layer": "transportation",
    //   filter: [
    //     "all",
    //     ["==", ["geometry-type"], "LineString"],
    //     [
    //       "all",
    //       ["==", ["get", "brunnel"], "bridge"],
    //       ["==", ["get", "class"], "minor_road"],
    //     ],
    //   ],
    //   layout: { "line-cap": "butt", "line-join": "miter", visibility: "none" },
    //   paint: {
    //     "line-color": "#dedede",
    //     "line-gap-width": [
    //       "interpolate",
    //       ["exponential", 1.55],
    //       ["zoom"],
    //       4,
    //       0.25,
    //       20,
    //       30,
    //     ],
    //     "line-width": [
    //       "interpolate",
    //       ["exponential", 1.6],
    //       ["zoom"],
    //       12,
    //       0.5,
    //       20,
    //       10,
    //     ],
    //   },
    // },
    // {
    //   id: "bridge_major case",
    //   type: "line",
    //   source: "openmaptiles",
    //   "source-layer": "transportation",
    //   filter: [
    //     "all",
    //     ["==", ["geometry-type"], "LineString"],
    //     [
    //       "all",
    //       ["==", ["get", "brunnel"], "bridge"],
    //       [
    //         "match",
    //         ["get", "class"],
    //         ["primary", "secondary", "tertiary", "trunk"],
    //         true,
    //         false,
    //       ],
    //     ],
    //   ],
    //   layout: { "line-cap": "butt", "line-join": "miter", visibility: "none" },
    //   paint: {
    //     "line-color": "#dedede",
    //     "line-gap-width": [
    //       "interpolate",
    //       ["exponential", 1.55],
    //       ["zoom"],
    //       4,
    //       0.25,
    //       20,
    //       30,
    //     ],
    //     "line-width": [
    //       "interpolate",
    //       ["exponential", 1.6],
    //       ["zoom"],
    //       12,
    //       0.5,
    //       20,
    //       10,
    //     ],
    //   },
    // },
    {
      id: "bridge_minor",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        [
          "all",
          ["==", ["get", "brunnel"], "bridge"],
          ["==", ["get", "class"], "minor_road"],
        ],
      ],
      layout: { "line-cap": "round", "line-join": "round", visibility: "none" },
      paint: {
        "line-color": "#efefef",
        "line-width": [
          "interpolate",
          ["exponential", 1.55],
          ["zoom"],
          4,
          0.25,
          20,
          30,
        ],
      },
    },
    {
      id: "bridge_major",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        [
          "all",
          ["==", ["get", "brunnel"], "bridge"],
          [
            "match",
            ["get", "class"],
            ["primary", "secondary", "tertiary", "trunk"],
            true,
            false,
          ],
        ],
      ],
      layout: { "line-cap": "round", "line-join": "round", visibility: "none" },
      paint: {
        "line-color": "#797B77",
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          6,
          0.5,
          20,
          30,
        ],
      },
    },
    // {
    //   id: "admin_sub",
    //   type: "line",
    //   source: "openmaptiles",
    //   "source-layer": "boundary",
    //   filter: ["match", ["get", "admin_level"], [4, 6, 8], true, false],
    //   layout: { visibility: "none" },
    //   paint: { "line-color": "hsl(0,0%,76%)", "line-dasharray": [2, 1] },
    // },
    // {
    //   id: "admin_country_z0-4",
    //   type: "line",
    //   source: "openmaptiles",
    //   "source-layer": "boundary",
    //   maxzoom: 5,
    //   filter: [
    //     "all",
    //     ["<=", ["get", "admin_level"], 2],
    //     ["==", ["geometry-type"], "LineString"],
    //     ["!", ["has", "claimed_by"]],
    //   ],
    //   layout: { "line-cap": "round", "line-join": "round", visibility: "none" },
    //   paint: {
    //     "line-color": "hsla(0,8%,22%,0.51)",
    //     "line-width": [
    //       "interpolate",
    //       ["exponential", 1.3],
    //       ["zoom"],
    //       3,
    //       0.5,
    //       22,
    //       15,
    //     ],
    //   },
    // },
    // {
    //   id: "admin_country_z5-",
    //   type: "line",
    //   source: "openmaptiles",
    //   "source-layer": "boundary",
    //   minzoom: 5,
    //   filter: [
    //     "all",
    //     ["<=", ["get", "admin_level"], 2],
    //     ["==", ["geometry-type"], "LineString"],
    //   ],
    //   layout: { "line-cap": "round", "line-join": "round", visibility: "none" },
    //   paint: {
    //     "line-color": "hsla(0,8%,22%,0.51)",
    //     "line-width": [
    //       "interpolate",
    //       ["exponential", 1.3],
    //       ["zoom"],
    //       3,
    //       0.5,
    //       22,
    //       15,
    //     ],
    //   },
    // },
  ],
};
