import type { StyleSpecification } from "maplibre-gl";

export const roads: StyleSpecification = {
  version: 8,
  name: "Water and Roads",
  center: [8.54806714892635, 47.37180823552663],
  zoom: 12.241790506353492,
  bearing: 0,
  pitch: 0,
  sources: {
    openmaptiles: {
      type: "vector",
      url: "https://tiles.basemaps.cartocdn.com/vector/carto.streets/v1/tiles.json",
      attribution:
        '<a href="https://www.openmaptiles.org/" target="_blank">&copy; OpenMapTiles!</a> <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>',
    },
  },
  layers: [
    {
      id: "tunnel_railway_transit",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 0,
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["==", ["get", "brunnel"], "tunnel"],
        ["==", ["get", "class"], "transit"],
      ],
      layout: {
        "line-cap": "butt",
        "line-join": "miter",
        visibility: "visible",
      },
      paint: {
        "line-color": "hsl(34,12%,66%)",
        "line-dasharray": [3, 3],
        "line-opacity": ["interpolate", ["linear"], ["zoom"], 11, 0, 16, 1],
      },
    },
    {
      id: "road_area_pier",
      type: "fill",
      metadata: {},
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "Polygon"],
        ["==", ["get", "class"], "pier"],
      ],
      layout: { visibility: "visible" },
      paint: { "fill-antialias": true, "fill-color": "#797B77" },
    },
    {
      id: "road_pier",
      type: "line",
      metadata: {},
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["match", ["get", "class"], ["pier"], true, false],
      ],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "visible",
      },
      paint: {
        "line-color": "#797B77",
        "line-width": [
          "interpolate",
          ["exponential", 1.2],
          ["zoom"],
          15,
          1,
          17,
          4,
        ],
      },
    },
    {
      id: "road_bridge_area",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "Polygon"],
        ["match", ["get", "brunnel"], ["bridge"], true, false],
      ],
      layout: { visibility: "visible" },
      paint: { "fill-color": "#797B77" },
    },
    {
      id: "road_trunk_primary",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["match", ["get", "class"], ["primary", "trunk"], true, false],
      ],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "visible",
      },
      paint: {
        "line-color": "#797B77",
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          2,
          0.1,
          20,
          30,
        ],
      },
    },
    {
      id: "road_secondary_tertiary",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["match", ["get", "class"], ["secondary", "tertiary"], true, false],
      ],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "visible",
      },
      paint: {
        "line-color": "#797B77",
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          6,
          0.5,
          20,
          20,
        ],
      },
    },
    {
      id: "road_major_motorway",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        ["==", ["get", "class"], "motorway"],
      ],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "visible",
      },
      paint: {
        "line-color": "#797B77",
        "line-offset": 0,
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          2.2,
          0.5,
          16,
          10,
        ],
      },
    },
    {
      id: "railway_transit",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["get", "class"], "transit"],
        ["!=", ["get", "brunnel"], "tunnel"],
      ],
      layout: { visibility: "visible" },
      paint: {
        "line-color": "hsl(34,12%,66%)",
        "line-opacity": ["interpolate", ["linear"], ["zoom"], 11, 0, 16, 1],
      },
    },
    {
      id: "railway",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: ["==", ["get", "class"], "rail"],
      layout: { visibility: "visible" },
      paint: {
        "line-color": "hsl(34,12%,66%)",
        "line-opacity": ["interpolate", ["linear"], ["zoom"], 11, 0, 16, 1],
      },
    },
    {
      id: "bridge_minor",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        [
          "all",
          ["==", ["get", "brunnel"], "bridge"],
          ["==", ["get", "class"], "minor_road"],
        ],
      ],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "visible",
      },
      paint: {
        "line-color": "#efefef",
        "line-width": [
          "interpolate",
          ["exponential", 1.55],
          ["zoom"],
          4,
          0.25,
          20,
          30,
        ],
      },
    },
    {
      id: "bridge_major",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        ["==", ["geometry-type"], "LineString"],
        [
          "all",
          ["==", ["get", "brunnel"], "bridge"],
          [
            "match",
            ["get", "class"],
            ["primary", "secondary", "tertiary", "trunk"],
            true,
            false,
          ],
        ],
      ],
      layout: {
        "line-cap": "round",
        "line-join": "round",
        visibility: "visible",
      },
      paint: {
        "line-color": "#797B77",
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          6,
          0.5,
          20,
          30,
        ],
      },
    },
  ],
};
