name: Deploy

on:
  push:
    branches:
      - feature/dev

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Node Version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install NPM Packages
        run: npm install

      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan "${{ secrets.REMOTE_HOST}}" >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.DH_SSH_KEY }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add /home/runner/.ssh/github_actions

      - name: Move Bash Scripts
        run: |
          mv ./.github/workflows/*.sh .
          chmod +x deploy.sh

      - name: Run Deploy
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          BRANCH: ${{ github.head_ref || github.ref_name }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
          DH_SSH_KEY: ${{ secrets.DH_SSH_KEY }}
        run: ./deploy.sh
